language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - echo "nothing needs to be installed"

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy reverseproxy
  - docker tag udagram-api-user udagram-api-user:latest
  - docker tag udagram-api-feed udagram-api-feed:latest
  - docker tag udagram-frontend udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push reverseproxy:latest
  - docker push udagram-api-user:latest
  - docker push udagram-api-feed:latest
  - docker push udagram-frontend:latest
