language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - echo "nothing needs to be installed"

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy shollsdoc/reverseproxy:v3
  - docker tag udagram-api-user shollsdoc/udagram-api-user:v3
  - docker tag udagram-api-feed shollsdoc/udagram-api-feed:v3
  - docker tag udagram-frontend shollsdoc/udagram-frontend:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shollsdoc/reverseproxy
  - docker push shollsdoc/udagram-api-user
  - docker push shollsdoc/udagram-api-feed
  - docker push shollsdoc/udagram-frontend